### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by BizCub** [0vergrown/Origins-Dietary-Delights#2]
Not a issue, but can you tell me how to make a mod from a datapack. I know that I need to somehow use some code from git modrinth, but I don't know how. Thank you in advance

**Comment by 0vergrown** [comment]
You mean convert a datapack into a mod?

**Comment by BizCub** [comment]
exactly

**Comment by 0vergrown** [comment]
I use Modrinth, if you upload a data pack, you get the option to turn it into a mod but you don't have to even make it public, you can just convert it into a mod and delete it if you want to even. That's it really

**Comment by BizCub** [comment]
Got it, thank you very much
