### ISSUE TITLE
Not working with 1.12.1 of Origins

### ISSUE THREAD

**Issue by Akinesis** [0vergrown/Origins-Dietary-Delights#7]
Directory for tags is now origins/tags/item

Without he S at the end.
So the tags are not recognized.

**Comment by 0vergrown** [comment]
> Directory for tags is now origins/tags/item
> 
> Without he S at the end.
> So the tags are not recognized.

Yes, I am aware. Currently, Origins for 1.21 is in Alpha, and I don't know if it works for 1.21.1 but they have also not updated their file structure to go from plural to single, I know it's planned but it hasn't happened which is what I'm waiting for, I also have to rework the pack to include the new 'minecraft:meat` tags they made and added and there are other changes which I have to figure out to maintain backwards compatibility and forward compatibility too. I'm waiting for Origins to stabilize, and I've been playing with tags and items to hopefully come up with a system that can preserve all features regardless of version. Please be patient, I promise that when Origins stabilizes, I'll update and hopefully would have found a way to keep compatibility throughout all versions

**Comment by 0vergrown** [comment]
Updated and fixed for newer versions. Everything should work now. Go to the download page to get versions for older versions of the game if needed.
